### ISSUE TITLE
Flashing border/decoration space

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#137]
This was changed within 3 weeks: Before there were decorations around wargus window. Now there is solid color that flashes on mouse clicks (e.g. selecting units).

By decorations I mean the area under the minimap and the tools on the left and this one centimeter bar on top, right and bottom.

**Comment by timfel** [comment]
Can you post a screenshot?

**Comment by mimooh** [comment]
![w2](https://cloud.githubusercontent.com/assets/14321180/11687326/570a5c36-9e86-11e5-8bce-312a4922ef9e.png)

**Comment by timfel** [comment]
Oh, I've seen this, this is related to opengl rendering. I didn't look too much into it, because the issue is really that there are missing images in your dataset (there should be borders from png images rendered around the entire screen). But I will look into it nonetheless

**Comment by timfel** [comment]
In the meantime, if you're not using the opengl pixel scaling anyway, you should be able to pass `-x -1` and the issue should go away for the time being

**Comment by mimooh** [comment]
The problem is related to user configs in ~/.stratagus directory. If I delete ~/.stratagus the menu decorations are back. I hope to debug it some day. -x -1 doesn't change anything for me.

**Comment by mimooh** [comment]
OK, so the problem happens when I check "use OpenGL". Then after one of two restarts of wargus the decorations are missing. They are back if I uncheck "use OpenGL". It may be related to some conversions of graphics - also, the game is slower to start because there are lots of conversions for OpenGL (only a few without OpenGL) - I am talking about these quick messages at the bottom after the server presses "Start game" in setup room.

BTW, are these gfx conversions (with/without OpenGL) always to be repeated? Is it that gfx is prepared for the given resolution and the files need to be converted? Perhaps it would be better to have them prerendered for any given resolution - they wouldn't be that heavy, right?

BTW, what's the purpose of OpenGL here? It would be for 3D data operations. How wargus gfx engine benefit from it?

**Comment by timfel** [comment]
@mimooh:

1: OpenGL is not just for 3d. It can be used for 2d accelleration, and in our case, it is used (for example), to implement the scaling effects (-Z and -x options).

2: The slower loading is *not* about scaling. It's because we need to convert the images into 32-bit opengl textures. This cannot really be cached, one could convert all graphics to 32-bit in advance, so they are there in the right format, but if we did this completely, that would have to be done for all player colors and for all color cycled palettes, so you'd probably get ~24x increase in your graphics folder.
