### ISSUE TITLE
Circle of power not working as an objective

### ISSUE THREAD

**Issue by sheepo99** [Wargus/wargus#141]
After playing through mission 2 of the human tides of darkness campaign ( goal: bring 1 elven archer to the circle of power) it turns out completing the objective does not end the mission as it should.

**Comment by DinkyDyeAussie** [comment]
I found this as well. I have been trying to pinpoint the problem in the scripts, but no luck yet. I will keep trying though.

**Comment by DinkyDyeAussie** [comment]
Some interesting things going on with this bug. The second human ToD mission is the only one not working properly. I tested the second orc mission where you rescue Zul'Jin and that one works. 

I also tested a backup self-contained copy of wargus 2.3 with the second human ToD mission, and it works as it should.

Thing is though, the script files "level02c_h.sms" for both 2.3 and 2.4 versions is written exactly the same way, and the 2.4 version of the game has the bug...I cannot fathom where on earth the bug is regarding the script files. It may even lie in the map definition file or even in the sourcecode, which is probably more likely.

I shall keep digging around. This is a weird bug.

**Comment by DinkyDyeAussie** [comment]
So here is the code in "level02c_h.sms" that checks if you have sent a rescued archer to the circle of power.

Triggers = [[
local cycle2Win = 120
AddTrigger(
  function() return GetPlayerData(6, "UnitTypesCount", "unit-archer") == 0 and
    IfRescuedNearUnit("this", ">=", 1, "unit-archer", "unit-circle-of-power") end,
  function()
	if (cycle2Win == 120) then
		PlaySound("rescue (human)")
	end
	cycle2Win = cycle2Win - 1
	if (cycle2Win <= 0) then
		ActionVictory() 
		return false
	end
	
  return true end)

I tried setting the "IfRescuedNearUnit" to "IfNearUnit" and the white archers you rescue still have no effect on victory. However, the blue archers make it work now - weird.

I reset it back to "IfRescuedNearUnit" and it's back to no archers affecting it. I tried setting the:

"IfRescuedNearUnit("this", ">=", 1, "unit-archer", "unit-circle-of-power") end," line to:
"IfRescuedNearUnit("this", "==", 1, "unit-archer", "unit-circle-of-power") end,"

...but that had no effect at all.

I will download the sourcecode and look at that. It's probably not that though, as the orc campaign works. so it looks like something to to with that map specifically and the circle of power in it.

**Comment by DinkyDyeAussie** [comment]
GOT IT!!! Bug has been fixed! In these two lines:

function() return GetPlayerData(6, "UnitTypesCount", "unit-archer") == 0 and
IfRescuedNearUnit("this", ">=", 1, "unit-archer", "unit-circle-of-power") end,

the "unit-archer", needs to be replaced with "unit-ranger", as there are 6 rangers, not archers that you rescue. Change this and it will execute the rescue sound and the victory condition!

**Comment by DinkyDyeAussie** [comment]
Don't know why but in wargus 2.3 they were archers, but in 2.4 they are rangers....hmmm...weird.
