### ISSUE TITLE
2.4 bugs

### ISSUE THREAD

**Issue by Mistranger** [Wargus/wargus#154]
I've missed 2.4 release (haven't touched Wargus since release of 2.3) and decided to look at it. Well, after months I've spent on polishing 2.3, looks like everything is right back when it started (bugs, bugs everywhere!)
This is small list of issues I've found:
2.3 has BNE CD support, 2.4 doesn't. Even README.md notes about it, while I've removed every "BNE not supported" label from 2.3 release.
Russian NSIS labels in installer are turned into unreadable mojibake.

**Comment by timfel** [comment]
The Battle.net comment in the README has not been touched since 2010 (https://github.com/Wargus/wargus/blame/master/README.md). It's wrong, too, because the (Linux) release is actually built with BNE support. I just didn't bother to update the readme. Compiling with StormLib on OSX currently doesn't work on Travis due to the specific OSX version. Somebody would need to just find out what to do there or which version works (Travis allows changing the version). For Windows, I just didn't bother to try.

And w.r.t the russion labels, I don't read russion, so when I updated the installer, I didn't bother with them. I don't see why they are needed, anyway, but if you want to fix them, go ahead.

In any case, could you file separate bugs for these issues?
