### ISSUE TITLE
keystrokes / mouse help

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#216]
I learned from commit logs that I can select more barracks with ctrl+click. Then I noticed additionally that shift+click on barrack shows where the trained units gather. There must be more of such I guess.

https://github.com/Wargus/wargus/blob/master/scripts/menus/help.lua is not providing this information. And it should. But I don't know where to learn about all these shortcuts. Any hint?

**Comment by timfel** [comment]
It's not the "Shift+Click", just pressing shift is enough, it shows the current selection's orders.

You can always Ctrl+Click to select all units of the same type, if indeed they are multi-selectable (we only recently made this possible for Barracks in Wargus, but not for all buildings).

So, yeah, the way keystrokes are handled through the code makes it difficult to automatically keep such help up to date.

For just keystrokes, I found these locations:
* interface.cpp `static bool CommandKey` has most of the shortcuts
* interface.cpp `int HandleKeyModifiersDown` has a quick return for screenshots
* interface.cpp `static void CommandKey_Group` has a various group-control functions, such as centering on a group, adding to a group, adding a group to the current selection, replacing a group with the current selection, selecting a group
* A global `HandleCommandKey` function in Lua
* Any hotkeys defined on Lua buttons that are shown in the button panel
* `map_draw.cpp:417` here is the logic that when you hold Shift, the orders of the current selection are shown

With mouse buttons, there are a ton of handler methods that sometimes do something special when you press Alt and/or Shift and/or Ctrl together with the left/right/middle mouse button:

mouse.cpp
* `DoRightButton_ForSelectedUnit`
 - RightClick+Shift => Command queue
 - RightClick+Alt+Ctrl => Ground attack
 - RightClick+Ctrl => Follow
 - RightClick+Alt => Defend

something special goes on when you right-click empty space
* `DoRightButton_Attack`
 - RightClick => When right button attack is set (the default), then move to the empty space
 - RightClick+Ctrl => When right button attack is set (the default), then move to the empty space in attack mode

* `MouseScrollMap`
 - When you hold Ctrl while scrolling the map with the mouse, it scrolls faster

* `UIHandleMouseMove`
 - There is some logic when you hold Alt and/or Shift while looking for a building location and your mouse cursor is showing the building. Not sure what that does.

* `UIHandleButtonUp`
 - There is a some logic here for selecting all air units or all ground units in a rectangle (instead of all), for adding a unit to a selection, for selecting the entire group that a unit belongs to, for selecting all units of the same type

* `SendMove`
  - Alt => Defend the goal

* `Send*` (almost all of them)
  - Shift => Add command to end of command queue

botpanel.cpp
* `DoClicked_SpellCast`, `DoClicked_Repair`
  - Ctrl => Enables auto-casting/auto-repair

editloop.cpp
* Ctrl+R => Randomize map
* Ctrl+M => Mirror edit

**Comment by mimooh** [comment]
Thanks for collecting all these. I will update the keystrokes help. 
Autocasting spells and operations on multiple barracks seems
particularly useful.

We keep hearing of openra project recently, so I installed it. It is
indeed very good piece of software, the installer of game data sets is
very nice and user friendly, but still I wouldn't exchange it for wargus
:)

-- 
Karol Kreński
tel. 517-302-055

**Comment by Erenussocrates** [comment]
I wonder if there is a way to make the Tips differentiate between orcs and humans to keep relevance. I mean, for example there is a tip saying "you can train more peasants in Town Hall", but in order to keep it relevance, it should be displaying "you can train more peons in Great Hall" if you are playing orcs. Is there a way to do that?

**Comment by timfel** [comment]
Keystrokes help was updated both for editor and main game
