### ISSUE TITLE
wargus stable vs unstable

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#223]
We need to have separate builds. I will first learn how it is supposed to be done for such projects (via branches I guess) and will try to setup it for wargus.

**Comment by timfel** [comment]
@mimooh I think we simply should be more careful with versions. For example, the current version should be 2.4.2-dev, rather than 2.4.1. Windows nightly builds at least are already separate, Linux builds should be ok when we have -dev versioning, only macOS needs to be fixed so we don't always overwrite the release.

**Comment by mimooh** [comment]
Yes, we should be working on 2.4.2 now, but two thing to consider:

a) for deb packages it seems the right way for the split is separate PPA
instead of adding '-dev' to package name (which would be fine for me
anyway):
https://www.debian.org/doc/manuals/repository-howto/repository-howto

b) except from binary packages we also need to release sources. Wouldn't
those belong to branches named 'v2.4.1', 'v2.4.2' and so on?

So you prefer that I learn it and take care of it, or it's just a quick
work for you? 

-- 
Karol Kreński
tel. 517-302-055

**Comment by timfel** [comment]
Each releasedl we create a tag, which identifies the source at the point in time of the release. We would only need branches for those if we planned to backport patches on to releases to fix bugs. Since this isn't libray software where people depend on some API not changing, I don't see a need for that. After all, branches are just pointers to some revision that can move, whereas tags are pointers that should not move. 

Regarding a separate ppa - sure, we can make a personal nighlty builds ppa and set the official one to manual builds. I don't think you have permissions to do that on the Stratagus launchpad, but if you do, go ahead.

**Comment by mimooh** [comment]
Ehhh, suddenly I noticed '2 releases' on Wargus/wargus and there's
source code too. I saw all that before, but was somehow blind :)

Downloads
Wargus-2.4.1.exe
Source code (zip)
Source code (tar.gz)

I will update wargus.github.io tomorrow.

No need for branches, the infrastructure is almost complete. Except that
PPA and osx builds. No, I don't have access to stratagus launchpad, but I
just sent a request to become a member.

**Comment by timfel** [comment]
I'm switching to update the name of the package to <version>-dev. Setting up a separate ppa is a hazzle. The windows releases are fine, and since I cannot test in osx at the moment at all, I'd consider these as "your mileage may vary", so nightly for those seems fine.
