### ISSUE TITLE
Starcraft Remastered, is it a threat for the future of Stratagus/Wargus?

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#235]
You know that blizzard has announced a remastered edition for the phenomical classic Starcraft. Considering this, if they decide to do the same thing for Warcraft 2 in the future as well, it could probably cause them to shut this project down once again. What are your thoughts?

**Comment by Kintobor** [comment]
With Starcraft it looks like they are re-rendering the old models. Starcraft is also really popular. Warcraft 2 doesn't have models, so I don't think it'll happen any time soon.

**Comment by timfel** [comment]
Since it looks like they just rerendered the old Starcraft models, we might be able to use them in Stargus. This might be a problem if we did it. With WC2, they could only do what we're already doing, that is, use some shaders or preprocessing to scale the graphics

**Comment by mimooh** [comment]
> Warcraft 2 doesn't have models, so I don't think it'll happen any time
According to the README.TXT file included alongside the Warcraft II demo
version, the graphics are pre-rendered 3D models. 
http://wowwiki.wikia.com/wiki/Warcraft_II:_Tides_of_Darkness

-- 
Karol Kreński

**Comment by Kintobor** [comment]
Pow! Bring on the Warcraft 2 Remastered!

**Comment by DinkyDyeAussie** [comment]
I imagine that stargus will probably just stagnate more, as Blizzard has remastered it, so what's the point in continuing with stargus, if Blizzard is now doing what stargus set out to do?

Also I read that they're not going to remaster Warcraft 2 or 1 now, which is shit because I love it...But I think gameplay wise the multiplayer would be good to remaster but the campaign in my eyes for some reason doesn't have the weight behind it to warrent one.

I am just rambling here, but I would probably still buy it if they did it for Warcraft 2. I'm gonna be buying the remastered starcraft though.
