### ISSUE TITLE
Missing TimGM6mb.sf2 SoundFont file from Ubuntu installation

### ISSUE THREAD

**Issue by pieqq** [Wargus/wargus#256]
Platform: Ubuntu 16.04

I just installed Wargus using the installation process described in the [main page](http://wargus.github.io/index.html). The game works but there was no music, and the following was displayed in the terminal:

```
fluidsynth: error: Unable to open file "music/TimGM6mb.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "music/TimGM6mb.sf2"
```

This is because the TimGM6mb SoundFont was indeed not available in the `~/.stratagus/data.Wargus/music/` directory. A quick search online pointed me to a link to download it and put it in the correct directory, and now I can get the music :)

Why is this SoundFont not part of the installation? Is it a license issue?

**Comment by a-detiste** [comment]
Hi,

It's already packaged in Ubuntu.

https://packages.ubuntu.com/zesty/timgm6mb-soundfont
https://packages.ubuntu.com/xenial/all/timgm6mb-soundfont/filelist

**Comment by timfel** [comment]
If you installed from the debian package, and the soundfont was not installed, then we just need to define the right dependency in the control file. Or did you install from source?

**Comment by pierrrrrrre** [comment]
@a-detiste : thanks for pointing this out! I hadn't even checked…
 
@timfel : I installed Wargus from the PPA, using the method described on the website (using the `ppa:stratagus` PPA).

So I think it's just a matter of adding a dependency in the `debian/control` file, but that may also require some adjustment in the game itself, since the [default path for the SoundFont is `music/TimGM6mb.sf2`](https://github.com/Wargus/wargus/blob/master/scripts/stratagus.lua#L403).

Please let me know if I can help :)

**Comment by timfel** [comment]
There is some old code in https://github.com/Wargus/wargus/blob/master/debian/postinst to copy the sound font to a global known directory. Given that, I guess we could copy it in the wartool.cpp. Although it may be easier just to bundle it (like we do on windows)

**Comment by pierrrrrrre** [comment]
Given that this SoundFont is only a few MB large, this could be an option.

Does it simply need to be added in the [`music`](https://github.com/Wargus/wargus/tree/master/music) directory?
