### ISSUE TITLE
The mouse cursor teleports around the screen every once in a while

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#259]
I know, the description of my problem really sounds a bit abstract, but it is what it is. Whenever I'm moving my mouse, there's a chance that the cursor instantly teleports to a corner or edge of the screen. It can happen both in-game and in menu. 
I'm playing Wargus in fullscreen and use OpenGL / OpenGL es 1.1 is also checked. I'm using Windows 10. This issue seems to happen only in fullscreen, and it happens with Wyrmsun too (another game that uses stratagus engine)

This issue really wasn't happening up until recently. I have been playing wargus from this same computer for quite a while, and such a problem didn't exist back then. But now this issue randomly started happening, and I have absolutely no idea why. Because of Windows updates?

**Comment by DinkyDyeAussie** [comment]
Don't think it is to do with windows updates but I have just downloaded 2.4.2 this morning and it did the same thing to me. Was about to start my own thread when I saw yours. Will follow to see what the devs say.

**Comment by MamiyaOtaru** [comment]
2.4.0 through 2.4.2 all exhibit this behavior for me.  Can work around by changing windows desktop resolution to whatever wargus is running, running wargus windowed, and using https://github.com/Codeusa/Borderless-Gaming to set it to borderless windowed fullscreen but it's a PITA

**Comment by MamiyaOtaru** [comment]
Wyrmsun had the same issue and appears to have fixed it with 
https://github.com/Andrettin/Wyrmgus/commit/dfd84ce95a4478d298186450d586543b36d07bb6
and maybe 
https://github.com/Andrettin/Wyrmgus/commit/2d5ea15335c79c77179e2d22553f2479d58669d3

**Comment by Peacemaker80** [comment]
Hello,
i have the sam issue here. It works fine since 1 year with windows 10 Home 1703. Today my systen installed Fall Update 1709 and the mouse teleports starts also on my warguis installation. It teleports also with war1gus. So it seems to be a problem with stratagus and windows 10 ver1709. The guys working on the project CNCNet have had the same poblem and fixed it. https://forums.cncnet.org/topic/7898-windows-10-fall-creators-update-issues/ 
I tested also the windows dpi overwrite function. Its very frustrating.
Does anybody have another idea or workaround?

**Comment by timfel** [comment]
@MamiyaOtaru The Wyrmsun fixes look like they would help. I probably won't have time to apply them to stratagus this weekend, so a PR would be very welcome :) Otherwise, I'll do it next week.

**Comment by Peacemaker80** [comment]
Unfortunately i have no possibility to program anything and need compiled windows binaries. It does not hurry :-). I would be pleased only if the error is fixed. Many Thanks! Stratagus is a great job!

**Comment by Erenussocrates** [comment]
I would really appreciate the fix after such a long time, the same thing happened to my friend's Wargus as well. We will be eagerly awaiting for the fix.

**Comment by pasildan** [comment]
@Erenussocrates thanks my friend for this thread ^^ Thanks @timfel I will keep waiting your solution for it, I do have same problem with that sudden mouse movements.

**Comment by timfel** [comment]
I applied the mentioned commits from Wyrmgus, hope that helps.

**Comment by Erenussocrates** [comment]
@timfel thank you very much for the fix. Though I have modded my own game (but not the .exe file), so which files should I replace in order for fix to take effect? Is only .exe file enoguh?

**Comment by timfel** [comment]
Just the executable would be enough.
________________________________

**Comment by biouxtai** [comment]
Installed 2.4.1 today and this issue is still present. I am running wargus at 1920x1080, which matches my desktop resolution, in fullscreen. The teleport is random. but it snaps the mouse to the nearest corner to its move path. Meaning if I am moving the mouse towards the bottom right, but in the center of the screen, it will jump to the bottom right corner at some point.

**Comment by timfel** [comment]
@biouxtai That is expected, you would have to install a nightly 2.4.2

**Comment by timfel** [comment]
Fixed in trunk
