### ISSUE TITLE
Go back to Wargus 2.1!

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#279]
Seriously. What have we actually done for Wargus/stratagus since version 2.1? It works more closely to the original Warcraft 2 than any version since.

I know alot of things have been added since, but alot of things have also been removed, and that has really messed up the code alot. Some things that used to belong in the engine code are now in the Lua script files and vice-versa.

I really just like 2.1 better. With a couple of code changes it will look, sound and play just like the original. The newer versions just have too many dependencies imo.

I think what happened was BOSWARS. That development team stripped alot of Warcraft features out of stratagus.

OK rant over....

**Comment by Kintobor** [comment]
I like Wargus 2.3.

**Comment by DinkyDyeAussie** [comment]
Things I've noticed is as soon as version 2.2 came out, the code in the engine changed to a more simplified format, and the .C files changed to .cpp.

Also the screen fades were gone. I have yet to test this but I don't know why the Devs had to change so much just because they were working on BOSWARS. They should've kept a good thing going.

I want to update the code in 2.1 to include the movies and the music from the original game but keep the code simple.

**Comment by timfel** [comment]
the question if wargus should be a faithful recreation of Warcraft II or something that is close, but can have it's own character was never really clearly answered afaict. I agree, Wargus 2.1 was one of the closest versions and back then my only contribution was to make the videos behave more closely to how they behave in the original. I keep a bundle of Wargus 2.1 for Windows and Linux around on some old hard drive just for having something so close to the original.

Since then Wargus has become more something that tries to evoke the Warcraft II feeling, but it still is it's own game, with slightly different mechanics, other options, the AI behaves slightly differently, and more such things. I don't think that's a bad thing. Thank's to the power of version control and how easy it is on Github to fork something, everyone can make from it what they want.

I personally use 2.4.1 these days, because it works for my friends with a Mac, I can launch a server from the commandline, and I like to use the shaders to make it look like I play on a CRT. But I don't view it as "Warcraft" anymore, it's just a nice classic RTS with graphics that I like and a soundtrack I enjoy.

**Comment by timfel** [comment]
I'm closing this issue, since this isn't really anything to "fix" as such. We can still have the conversation on the closed issue.
